apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenant1
  namespace: apps
spec:
  interval: 5m0s
  path: ./sample-app-1
  prune: true
  serviceAccountName: tenant1
  sourceRef:
    kind: GitRepository
    name: tenant1
  validation: client