apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  # labels:
  #   toolkit.fluxcd.io/tenant: tenant1
  name: sample-app-1-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:apps:reconciler
- kind: ServiceAccount
  name: sample-app-1
